name: .NET Core

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.ps1'
      - '**/parse-posts.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Install dependencies
      working-directory: ./src/Blazog
      run: dotnet restore
    - name: Build
      working-directory: ./src/Blazog
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./src/Blazog
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      working-directory: ./src/Blazog
      run: dotnet publish --configuration Release --no-restore
    - name: Copy to blob storage
      uses: Azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: >
          az storage blob upload-batch
          -s $GITHUB_WORKSPACE/src/Blazog/bin/Release/netstandard2.1/publish/wwwroot
          -d \$web
          --connection-string '${{ secrets.STORAGE_CONNECTION_STRING }}'