name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    - name: Install dependencies
      working-directory: ./src/Blazog
      run: dotnet restore
    - name: Build
      working-directory: ./src/Blazog
      run: dotnet build --configuration Release --no-restore
    - name: Test
      working-directory: ./src/Blazog
      run: dotnet test --no-restore --verbosity normal
