name: Parse posts

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.ps1'
      - '**/parse-posts.yml'
    
jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate JSON Output
        shell: pwsh
        working-directory: ./eng
        run: Get-Location
        # run: .\GenerateData.ps1 -postDir '..\posts' -dataDir '..\data'
