name: Parse posts

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.ps1'
      - '**/parse-posts.yml'
    
jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Generate JSON Output
        shell: pwsh
        run: ..\..\eng\GenerateData.ps1
