name: Parse posts

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.ps1'
      - '**/parse-posts.yml'
    
jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Display dir
        run: dir
        shell: cmd
      - name: Generate JSON Output
        run: .\eng\GenerateData.ps1
        shell: pwsh
