name: Parse posts

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.ps1'
      - '**/parse-posts.yml'
    
jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Output Get-Location
        run: Get-Location
        shell: pwsh
      - name: Output Get-ChildItem
        run: Get-ChildItem | Out-String
        shell: pwsh
      - name: Generate JSON Output
        run: .\eng\GenerateData.ps1
        shell: pwsh
