name: Parse posts

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.ps1'
      - '**/parse-posts.yml'
    
jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Generate JSON Output
        shell: pwsh
        working-directory: ./eng
        run: .\GenerateData.ps1 -postDir '$GITHUB_WORKSPACE/posts' -dataDir '$GITHUB_WORKSPACE/data'
