name: Parse posts

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.ps1'
    
jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          inlineScript: >
            .\eng\GenerateData.ps1
