name: Parse posts

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.ps1'
      - '**/parse-posts.yml'
    
jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate JSON Output
        shell: pwsh
        run: .\eng\GenerateData.ps1 -postDir '.\posts' -dataDir '.\data'
      - name: Copy to blob storage
        uses: Azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: >
            az storage blob upload-batch
            -s $GITHUB_WORKSPACE/data
            -d \$web
            --destination-path data  
            --connection-string '${{ secrets.STORAGE_CONNECTION_STRING }}'
