name: Parse posts

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.ps1'
    
jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Output location
        run: echo Get-Location
        shell: pwsh

    steps:
      - name: Generate JSON Output
        run: .\eng\GenerateData.ps1
        shell: pwsh
